---
phases:
  build:
    commands:
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - REPOSITORY_URI=462069092803.dkr.ecr.eu-west-1.amazonaws.com/inspire-oapif-demo
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - git submodule foreach git pull origin master
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      #- "docker build -t tervo/inspire-oapif-demo ."
      #- "docker tag tervo/inspire-oapif-demo 462069092803.dkr.ecr.eu-west-1.amazonaws.com/inspire-oapif-demo:latest"
  post_build:
    commands:
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - REPOSITORY_URI=462069092803.dkr.ecr.eu-west-1.amazonaws.com/inspire-oapif-demo
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      #- "docker push 462069092803.dkr.ecr.eu-west-1.amazonaws.com/inspire-oapif-demo:latest"
  pre_build:
    commands:
      - "echo Logging in to Docker Hub..."
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=462069092803.dkr.ecr.eu-west-1.amazonaws.com/inspire-oapif-demo
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      #- "docker login --username=\"dvohra\" --password=\"password\""
artifacts:
  files: imagedefinitions.json
version: 0.2
